spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: slc
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: s_slack
  application:
    name: slack
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: default
  profiles:
    include: private


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
    port: 19095