spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: slack_user
    password: slack_user

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: slack
  application:
    name: slack
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: default
  profiles:
    include: private
