spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: s_user  # 기본 스키마 설정
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: usr
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: s_user

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


server:
  port: 8081
