version: '3.8'

services:
  postgres:
    image: postgres:15.8
    restart: always
    volumes:
      - ./db/msa_ai_local:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis:7.0
    restart: always
    volumes:
      - ./db/msa_ai_local:/var/lib/redis/data
    ports:
      - "6379:6379"
    environment:
      REDIS_USER: default
      REDIS_PASSWORD: default
