-- 스키마 생성
CREATE SCHEMA S_AI;
CREATE SCHEMA S_COMPANY_PRODUCT;
CREATE SCHEMA S_HUB;
CREATE SCHEMA S_ORDER_DELIVERY;
CREATE SCHEMA S_SLACK;
CREATE SCHEMA S_USER;


-- 사용자 생성
CREATE USER AIU WITH PASSWORD '1234';
CREATE USER CPR WITH PASSWORD '1234';
CREATE USER HUB WITH PASSWORD '1234';
CREATE USER ODL WITH PASSWORD '1234';
CREATE USER SLC  WITH PASSWORD '1234';
CREATE USER USR WITH PASSWORD '1234';

-- 권한 부여
GRANT ALL PRIVILEGES ON SCHEMA S_AI TO AIU ;
GRANT ALL PRIVILEGES ON SCHEMA S_COMPANY_PRODUCT TO CPR ;
GRANT ALL PRIVILEGES ON SCHEMA S_HUB TO HUB;
GRANT ALL PRIVILEGES ON SCHEMA S_ORDER_DELIVERY TO ODL ;
GRANT ALL PRIVILEGES ON SCHEMA S_SLACK TO SLC  ;
GRANT ALL PRIVILEGES ON SCHEMA S_USER TO USR ;