spring:
  application:
    name: company-product

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: cpr
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 19092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

gemini:
  base-url: ${GEMINI_BASE_URL}

googleai:
  api:
    key: ${GEMINI_API_KEY}